/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_kaiwen_JniTest */

#ifndef _Included_com_kaiwen_JniTest
#define _Included_com_kaiwen_JniTest
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_kaiwen_JniTest
 * Method:    strFromJni
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_kaiwen_JniTest_strFromJni
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
