obj-m += space_kern.o

KID := /lib/modules/`uname -r`/build
PWD := $(shell pwd)

all:
	make -C $(KID) M=$(PWD) modules
	gcc -o space_user space_user.c
clean:
	rm -rf *.o .cmd *.ko *.mod.c .tmp_versions space_user
